add 방과후 목록 엔티티
GSM-MSG/GCMS-ADMIN-Backend pull request #18
Opened 2022-06-03 03:40 UTC by dolong2

## 한일
* 방과후 목록 엔티티 추가
* 학년 엔티티 추가
* 요일 엔티티 추가

## 원해여
* 코드 리뷰점 빡세게 해주세여

2022-06-03 03:57 UTC, baekteun approved these changes
🤔

2022-06-03 03:57 UTC, baekteun approved these changes
코드 리뷰를 하기에는 자바라 힘드네요

2022-06-03 04:29 UTC, khs3994 approved these changes

2022-06-03 06:02 UTC, louis7308 requested changes
approve 잘못때림

2022-06-04 06:28 UTC, louis7308 approved these changes

2022-06-04 06:28 UTC, merged