Spring boot Security JWT 도입...
GSM-MSG/GCMS-ADMIN-Backend pull request #26
Opened 2022-06-21 14:07 UTC by louis7308

* AccessToken, RefreshToken 도입
* 어드민페이지라 로그인 하는 부분 빼고 전부 토큰 필요

2022-06-21 14:08 UTC, Huuuunee approved these changes

2022-06-21 14:09 UTC, yoonjibin approved these changes
good

2022-06-21 14:12 UTC, chanwoo00106 approved these changes

2022-06-21 14:27 UTC, baekteun requested changes

2022-06-21 14:27 UTC, baekteun commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
개발하시느라 수고하셧습니다 ㅎㅎ
UserDetails의 구현체를 따로 빼시는건 어떻게 생각하시나요??
위의 코드를 보시면 Entity객체에 SpringSecurity 스펙인 UserDetails를 구현하도록 하신 것 같아요.
하지만 Entity는 최상위 비즈니스 로직에 해당되기 때문에, UserDetails같은 하위 비즈니스 로직에 의존하지 않는편이 좋다고 생각해요.

MyUserDetails 같은 클래스를 만들어 해당 클래스에서 User의 Id나 이메일값과, UserDetails스팩을 적용시키면 조금더 아키텍처 적으로 좋은 코드가 될 수 있을 것 같아요!
좋은 코드 작성해주셔서 감사합니다 -지인호-

2022-06-21 14:27 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +    @PostMapping("/login")
Controller 의 endpoint메서드의 반환값을 ResponseEntity로 래핑하는건 어떻게 생각하시나요?
해당 코드에서는 @ResponseStatus 어노테이션을 사용해 HttpStatus를 지정하고, 반환값을 Service의 반환을 그대로 반환하고 있습니다.
ResponseEntity를 사용할 경우, @ResponseStatus와 return value로 파편화된 response information을 하나로 통합할 수 있을 것 같아요!
가독성이 좋아지는건 덤이구요
좋은 저녁 되세요 ㅎㅎ

2022-06-21 14:27 UTC, baekteun commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +    private String email;
Dto는 불변성을 보장하도록 설계하는게 좋아보여요!
현재 코드를 보시면 NoArgsConstructor를 통해, email이 Null인 상태로 인스턴스를 생성할 수 있고
@Setter를 통해 email의 값을 변조할 수 있어요!
이를 통해 같은 Dto레퍼런스값을 참조하고있는 여러 서비스가 존재할때, 데이터의 무결성을 파손시키는 경우가 생길 수 있습니다!

email필드를 final로 지정하고, @Setter와 @XXXArgsConstructor를 지우고, @RequiredArgsConstructor를적용하여 불변성을 보장하도록 재설계하는건 어떠신가요?
혹은현재 프로젝트가 java16이상의 버전을 사용하고있다면, record라는 spec을 적용하는것도 좋아보입니다!
-지인호-

2022-06-21 14:27 UTC, baekteun commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +        return map;
responseDTO를 만드는게 더 가독성이 좋을듯

2022-06-21 14:28 UTC, baekteun commented
[5cdf68e](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/5cdf68ee47329eddaf8cd7980967bd51d95fbd73) 커밋 내역 보면 ✨ 인데 ➕ 라는 add dependency gitmoji 있음

2022-06-21 14:32 UTC, khs3994 approved these changes

2022-06-21 14:37 UTC, baekteun requested changes

2022-06-21 14:37 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +    private final MyUserDetailService myUserDetailService;
myUserDefailsService는 TokenProvider에 넣는게 나을듯?

2022-06-21 14:37 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
request갈때 Authotization에 accessToken만 보낼거같은데 굳이 refresh도 같이 보내야 하는 이유가 없을거같은데 accessToekn

2022-06-21 14:39 UTC, kimsh153 approved these changes

2022-06-21 14:47 UTC, sagwamatrlawns approved these changes

2022-06-22 01:52 UTC, dolong2 approved these changes

2022-06-22 01:52 UTC, dolong2 commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
로그인 유지떔에 넣은거 같은데

2022-06-22 05:07 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
이건 뭐 어째야 되냐

2022-06-22 06:27 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
로그인 유지되는 로직이
클라이언트가 서버에서 받은 토큰의 유효기간 검증 후 refresh요청 해서 로그인 유지하는 로직이 있고

서버에 access담아서 reqeust해서 401뜨면 그때 refresh하는 요청을 보낸 다음 reqeust를 retry하면서 유지하는 방법을 쓸텐데

애초에 둘 다 보내서 둘 다 검증하는거부터 굳이?라는 느낌이 드는데 how to think @louis7308

2022-06-22 06:31 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +    private final MyUserDetailService myUserDetailService;
Filter에서 로직을 처리하다니 이건 아니지

2022-06-22 06:32 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +    private final MyUserDetailService myUserDetailService;
수정했으

2022-06-22 06:33 UTC, baekteun commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
Comment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎComment 를 잘 못보셧나요?
개선의지가 없으신가봐요 ㅎㅎ

2022-06-22 06:34 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
?? 어디 실수함?

2022-06-22 06:34 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
근데 나는 아직 커밋을 전부 안올렸는데 어케 본거지?

2022-06-22 06:35 UTC, key-del-jeeinho commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-06-22 06:40 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
해결했습니다.

2022-06-22 06:41 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +    @PostMapping("/login")
해결했습니다.

2022-06-22 06:41 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +    private String email;
이부분은 어떻게 건들여야 될지 몰라서 따로 @NotNULL로 Vaild 먹여서 해결했습니다.

2022-06-22 06:42 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +        return map;
해결

2022-06-22 07:00 UTC, baekteun commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +        }
ofElseThrow로 null을 검사 했는데 다시 user를 검증할 필요가 없어보여요
```suggestion
                .orElseThrow(() -> new RuntimeException());
```

2022-06-22 07:00 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
UserNotFoundException이라고 이미 명시되어 있는데 constructor에 ErrorCode를 받는 과정은 불필요해보입니다.
클래스 이름에서 무슨 에러인지 명시하는 방법이라면 [InvalidTokenException](https://github.com/GSM-MSG/MSG-Backend_AfterSchool/blob/main/src/main/java/com/msg/after_school/global/security/exception/InvalidTokenException.java)코드같이 static 변수를 두는 방식 어떤가요? 아니면 이처럼 constructor를 받는 Exception하나를 따로 만드는 방법도 괜찮아보입니다.

2022-06-22 07:04 UTC, baekteun commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +import org.springframework.security.core.userdetails.UserDetails;
"Unused import"
```suggestion

```

2022-06-22 07:04 UTC, baekteun commented on src/main/java/com/example/msgadminapi/domain/repository/UserRepository.java
> +     Optional<User> findUserByEmail(String email);
```suggestion
    Optional<User> findUserByEmail(String email);
```
들여쓰기 간격이 좀 이상하군요

2022-06-22 07:05 UTC, baekteun commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +                .orElseThrow(() -> new RuntimeException());
이 친구는 왜 UserNotFoundException말고 RuntimeException을 걸어놨나요

2022-06-22 07:12 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +import io.jsonwebtoken.Jwt;
Unused import 아닌가요?
```suggestion
```

2022-06-22 07:12 UTC, baekteun commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +    }
refreshToken봐서 충동적으로 생긴 생각인데 redis 넣어서 해주셈

2022-06-22 07:12 UTC, baekteun commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +import com.sun.istack.NotNull;
dto단에서 쓰는 validator는 javax.validations인가 에서 가져올텐데 잘못 가져오신거같은데요?

2022-06-22 07:18 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
WebSecurityConfigurerAdapter를 상속받아서 SecurityConfig를 구성하는 방법은 슬프게도 Spring Security 5.7.0-M2에서 deprecated되었답니다. 제가 써 본 [reference](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) 드릴테니 위 글대로 해보시는거 어떤가요? 아니면 새로운 더 좋은 방법은 언제나 좋지요

2022-06-22 07:19 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
아 처음해본 JWT 라 이거 성공하면 5.7 버전으로 바꿀려고 했음

2022-06-22 07:20 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +import com.sun.istack.NotNull;
아 어쩐지

2022-06-22 07:20 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +    }
으으으으씹덕...

2022-06-22 07:21 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +import io.jsonwebtoken.Jwt;
수정했습니다

2022-06-22 07:21 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +import io.jsonwebtoken.Jwt;
suggestion했는데 직접 에디터에서 하지 말고 받는거 어떠신지요

2022-06-22 08:51 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +        return false;
[링크(https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/28e4b4e27af357c221eaa1425dc28139d7b9ee50)

2022-06-22 08:55 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +        return map;
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/dce33c066b0cff06ed6da91a80d1d0a4928439c7)

2022-06-22 09:05 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +    @PostMapping("/login")
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/4bd3a8c1b562f79980dd429afeeb7705a47c2092)

2022-06-22 09:23 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +    private String email;
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/421428505029d761579d40a26fc7e8ba432537be)

2022-06-22 09:24 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +    private final MyUserDetailService myUserDetailService;
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/e1ce4c912facebdb8fb8b295278380d85ac78afe)

2022-06-22 11:16 UTC, key-del-jeeinho commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
제생각에는 ErrorCode를 없애는것 보다는 Message를 Detail하게 작성하는게 좋아보여요!
String과는 달리 EnumType은 formatting된 value이기때문에 나중에 Exception을 세분화할때 좋아요.
또한, UserNotFindException의 상위클래스로 GlobalException을 두어, 예외를 추상화하고
누락된 에러들에 대한 로깅을할때도, getErrorType을 GlobalException에 정의해놓을 경우, 해당 Type을 통해 더욱 좋은 에러처리/로깅이 가능해보여요.

2022-06-22 11:22 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
아 전달과정에 약간 오해의 소지가 있는거 같아요. ErrorCode를 없애자는게 아니라 이미 UserNotFoundException이라는 이름이라면 ErrorCode의 USER_NOT_FOUND를 무조건 사용할텐데 여기같은 경우 constructor에 ErrorCode를 받아서 그 ErrorCode를 가지게되는데, 그 과정이 불필요해 보여서 말한거였어요

2022-06-22 11:23 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
근데 ErrorCode에 msg와 details라는 프로퍼티를 갖고 있는데 Exception에서 message를 또 받는군요 🤔

2022-06-22 11:24 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
아 ErrorClassfication?

2022-06-22 11:26 UTC, baekteun commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
https://github.com/GSM-MSG/GCMS-ADMIN-Backend/blob/d9697e53df0d6f1c25741661d7607859332400ec/src/main/java/com/example/msgadminapi/exception/Handler/GlobalExceptionHandler.java#L20-L24

@louis7308  🤔 🤔 🤔 🤔 🤔 🤔

2022-06-22 11:27 UTC, key-del-jeeinho commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
검증시에는 AccessToken(Authorization)만 사용하는게 좋을 것 같아요!
RefreshToken은 AccessToken이 만료되었을 경우, AccessToken을 재발급하기위한 용도로만 사용하는 토큰이에요.

AccessToken의 만료기한을 설정하지 않거나 길게 설정할 경우, AccessToken탈취시, 심각한 보안이슈가 발생할 수 있기 때문에, RefreshToken을 통해 일정시간주기로 서버에 재발급 요청을 하게 해줘요.
서버측에서 어느정도 AccessToken을 관리할 수 있게 해주는 용도로 쓰는거죠.

따라서, AccessToken재발급과는 도메인 연관성이 별로 없는 인증/인가 로직에 RefreshToken을 사용할 필요는 없어보입니다! :)

2022-06-22 12:03 UTC, baekteun commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +    }
@louis7308

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +                .orElseThrow(() -> new RuntimeException());
수정하겠습니다.

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +                .orElseThrow(() -> new RuntimeException());
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/95a4fbffbc67c296ff80f605f90aeb4d28316a50)

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +        }
해결했습니다.

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/UserService.java
> +        }
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/da2bfe4bc3da948e7cb99e0ed0f00a312088c33f)

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +import com.sun.istack.NotNull;
해결했습니다.

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/dto/request/SignInDto.java
> +import com.sun.istack.NotNull;
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/421428505029d761579d40a26fc7e8ba432537be)

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/UserController.java
> +import io.jsonwebtoken.Jwt;
해결완료 [링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/fe2d551847140cfe7fff41491a50d3ca4c57b806)

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
ErrorCode details 부분에서 ErrorClassfication 을 사용합니다.

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/auth/MyUserDetailService.java
> +                .orElseThrow(() -> new UserNotFindException("User Not Find", ErrorCode.USER_NOT_FIND));
해결했습니다. [링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/40cf2609fa2c4bd6bd179355f7b9ff589099b227)

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
해결했습니다.

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/jwt/JwtAuthenticationFilter.java
> +        String refreshToken = request.getHeader("RefreshToken");
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/73a2cb097204f49191c356daa2747d64ec9d1cde)

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +    }
해결완료

2022-06-26 02:11 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/domain/entity/user/User.java
> +    }
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/0cd8db92f343e1faa8cb660c49d83cf0d75765f0)

2022-06-26 02:18 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
해결완료

2022-06-26 02:18 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/configuration/security/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/67adf2aafc6efabe9c8d3d82a215b83ed598abb0)

2022-06-26 02:20 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    public ResponseEntity<RefreshResponseDto> refreshToken(@RequestBody RefreshTokenDto refreshTokenDto) {
Get인데 body? 맞아..?

2022-06-26 02:21 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    public ResponseEntity<RefreshResponseDto> refreshToken(@RequestBody RefreshTokenDto refreshTokenDto) {
받을순 있어 ㅎㅎ

2022-06-26 02:21 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    public ResponseEntity<RefreshResponseDto> refreshToken(@RequestBody RefreshTokenDto refreshTokenDto) {
걍 Param으로 할까?

2022-06-26 02:24 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    public ResponseEntity<RefreshResponseDto> refreshToken(@RequestBody RefreshTokenDto refreshTokenDto) {
하지만 보낼 수는 없지

2022-06-26 02:26 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    public ResponseEntity<RefreshResponseDto> refreshToken(@RequestBody RefreshTokenDto refreshTokenDto) {
해결

2022-06-26 02:26 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    public ResponseEntity<RefreshResponseDto> refreshToken(@RequestBody RefreshTokenDto refreshTokenDto) {
[링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/d6843c87ba5c58de7e5462e6c14e7cdf1797e9e4)

2022-06-26 02:32 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/MemberController.java
>          return responseService.getSuccessResult();
명세서 수정하고 관련된 클라이언트들한테 싹다 공지하셈

2022-06-26 02:32 UTC, baekteun commented on src/main/java/com/example/msgadminapi/service/TeacherService.java
> +    }
refreshToken은 refresh가 안되는데?
애초에 쓰지도 않는데 왜 파라미터로 받은거여?

2022-06-26 02:32 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    }
queryString에서 refresh토큰 받는거 미친짓인거같은데 Header에서 받아야하지 않을까요. 그리고 refreshToken만으로도 유저 찾을 수 있으니 email을 굳이 받을 필요도 없는거 같고

2022-06-26 02:33 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/TeacherService.java
> +    }
기존 refreshToken 보내주는거임 유효하다면

2022-06-26 02:34 UTC, baekteun commented on src/main/java/com/example/msgadminapi/service/TeacherService.java
> +    }
로그인 유지는?

2022-06-26 02:35 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/TeacherService.java
> +    }
로그인 유지는 1일 됨

2022-06-26 02:35 UTC, baekteun commented on src/main/java/com/example/msgadminapi/service/TeacherService.java
> +    }
지속적 로그인 유지가 되어야지

2022-06-26 03:20 UTC, baekteun commented on src/main/java/com/example/msgadminapi/exception/exception/TeacherNotFoundException.java
> +    private static CommonException EXCEPTION = new TeacherNotFoundException();
얘 private static이면 걍 의미 없는거 아님..?

2022-06-26 03:20 UTC, baekteun commented on src/main/java/com/example/msgadminapi/exception/exception/MemberNotFoundException.java
> +    }
예외 throw하는게 지금 어중간해진거 같은데..?

2022-06-26 03:57 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    }
refreshToken 만으로 유저를 어케 찾음??

2022-06-26 04:18 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +    }
해결완료 [링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/87f27dd5ee42cfee09c2847bda39576283506d26)

2022-06-26 04:19 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/service/TeacherService.java
> +    }
해결완료 [링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/f7c5c5ffd04f4c5d6143ef9383cbf8e0d8d0d6e1)

2022-06-26 04:20 UTC, baekteun commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +        RefreshResponseDto responseDto = teacherService.reIssueAccessToken(request.getHeader("RefreshToken"));
헤더에서 빼오는거 `@RequestHeader("Refresh-Token")` 이런식으로 할 수 있음

2022-06-26 04:24 UTC, louis7308 commented on src/main/java/com/example/msgadminapi/controller/TeacherController.java
> +        RefreshResponseDto responseDto = teacherService.reIssueAccessToken(request.getHeader("RefreshToken"));
수정 [링크](https://github.com/GSM-MSG/GCMS-ADMIN-Backend/pull/26/commits/ee08e750667fe30e2a8a03df3fe8aa865b68221e)

2022-06-26 04:25 UTC, baekteun approved these changes

2022-06-26 07:53 UTC, merged